"""Build source .blend files, render individual sprite sheets and generate manifests."""
from pathlib import Path
import argparse, json, os, shutil, sys

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path: sys.path.insert(0, str(SCRIPT_DIR))

import bpy
from config.pipeline_config import ASSETS, PALETTE_VERSION, QUALITY_PROFILE, RENDER_VERSION, project_root_from_script
from render_common import render_character_sheet, render_world_sheet
from reference_sprite_import import render_reference_assets
from normalize_sprite_sheets import normalize_world_assets
from source_builder import build_source_files

def output_paths(project_root, definition):
    category = definition["category"]
    base = project_root / "assets/pixel/rendered" / category
    return base / f"{definition['assetId']}.png", project_root / "assets/pixel/rendered/thumbnails" / f"{definition['assetId']}.png"

def deployed_paths(project_root, definition):
    category = definition["category"]
    base = project_root / "public/assets/pixel/rendered" / category
    return base / f"{definition['assetId']}.png", project_root / "public/assets/pixel/rendered/thumbnails" / f"{definition['assetId']}.png"

def render_assets(project_root: Path, selected=None, category=None):
    selected_ids = {selected} if isinstance(selected, str) else set(selected or [])
    definitions = [item for item in ASSETS if (not selected_ids or item["assetId"] in selected_ids) and (not category or item["kind"] == category)]
    loaded_source = None
    rendered = []
    for definition in definitions:
        source = project_root / definition["sourceBlend"]
        if not source.exists(): raise RuntimeError(f"Missing source blend: {source}")
        if loaded_source != source:
            bpy.ops.wm.open_mainfile(filepath=str(source)); loaded_source = source
        output, thumbnail = output_paths(project_root, definition)
        if definition["kind"] == "character": render_character_sheet(definition, output, thumbnail)
        else: render_world_sheet(definition, output, thumbnail)
        deployed_output, deployed_thumbnail = deployed_paths(project_root, definition)
        deployed_output.parent.mkdir(parents=True, exist_ok=True); deployed_thumbnail.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(output, deployed_output); shutil.copy2(thumbnail, deployed_thumbnail)
        rendered.append((definition, output, thumbnail))
        print(f"RENDERED {definition['assetId']} -> {output}")
    return rendered

def manifest_entry(project_root, definition, output, thumbnail):
    frame_count = sum(definition["animations"].values())
    deployed_output, deployed_thumbnail = deployed_paths(project_root, definition)
    return {
        **definition,
        "renderedFile": "/" + deployed_output.relative_to(project_root / "public").as_posix(),
        "spriteSheet": "/" + deployed_output.relative_to(project_root / "public").as_posix(),
        "thumbnail": "/" + deployed_thumbnail.relative_to(project_root / "public").as_posix(),
        "frameCount": frame_count,
        "paletteVersion": PALETTE_VERSION, "renderVersion": RENDER_VERSION,
        "transparent": True,
    }

def write_manifests(project_root: Path):
    entries = []
    for definition in ASSETS:
        output, thumbnail = output_paths(project_root, definition)
        entries.append(manifest_entry(project_root, definition, output, thumbnail))
    manifest = {"version": RENDER_VERSION, "qualityProfile": QUALITY_PROFILE, "camera": {"projection": "orthographic", "horizontalAngle": 45, "inclination": 35.264, "frameGrid": "64x32", "pixelFilter": "nearest", "supersampling": 1}, "assets": entries}
    json_path = project_root / "public/assets/pixel/rendered/asset-manifest.json"; json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    ts_path = project_root / "src/assets/pixel/blenderManifest.ts"
    compact = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    ts_path.write_text("// Generated by tools/blender/build_assets.py. Do not edit manually.\n"
                       "export interface BlenderRenderedAsset { assetId:string;kind:'character'|'furniture'|'equipment';category:string;renderedFile:string;spriteSheet:string;thumbnail:string;visualLevel:number;gameplayLevel?:number;equipmentFamilyId?:string|null;nextLevelAssetId?:string|null;footprint:number[];anchor:number[];orientations:string[];animations:Record<string,number>;frameCount:number;frameSize:number[];sourceBlend:string;sourceCollection:string;paletteVersion:string;renderVersion:string;transparent:boolean;interactionPoints:number[][];qualityProfile:string;nativeScale:number;logicalHeightBlocks?:number;referenceSource?:string;referenceMode?:string;}\n"
                       f"export const BLENDER_RENDERED_ASSETS = {compact} as BlenderRenderedAsset[];\n", encoding="utf-8")
    return json_path, ts_path

def build_all(project_root: Path, selected=None, category=None, rebuild_sources=True):
    if rebuild_sources: build_source_files(project_root)
    rendered = render_assets(project_root, selected, category)
    render_reference_assets(project_root, ASSETS, selected)
    normalize_world_assets(project_root, ASSETS, selected, category)
    manifests = write_manifests(project_root)
    return rendered, manifests

def parse_args():
    parser = argparse.ArgumentParser(); parser.add_argument("--asset"); parser.add_argument("--assets"); parser.add_argument("--category", choices=("character", "furniture", "equipment")); parser.add_argument("--skip-sources", action="store_true"); parser.add_argument("--project-root")
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    return parser.parse_args(args)

if __name__ == "__main__":
    args = parse_args(); root = Path(args.project_root).resolve() if args.project_root else project_root_from_script()
    selected = [item.strip() for item in args.assets.split(",") if item.strip()] if args.assets else args.asset
    rendered, manifests = build_all(root, selected, args.category, not args.skip_sources)
    preview_env = os.environ.get("BLENDER_CODEX_PREVIEW_PATH"); blend_env = os.environ.get("BLENDER_CODEX_BLEND_PATH")
    if preview_env and rendered: shutil.copy2(rendered[0][2], preview_env)
    if blend_env:
        source = root / (rendered[0][0]["sourceBlend"] if rendered else ASSETS[0]["sourceBlend"]); shutil.copy2(source, blend_env)
    print(f"MANIFEST {manifests[0]}")
